=== abington/Zend-Acl-Xml-Builder/src/chippyash/Zend/Acl/Xml/xsd/zendacl.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns="http://schema.zf4.biz/schema/zendacl"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://schema.zf4.biz/schema/zendacl"
    elementFormDefault="qualified"
    >
    <xs:annotation>
        <xs:documentation>
            <![CDATA[
      Zend ACL XML Services Schema, version 1.0
      Authors: Ashley Kitson
      
      This defines a way to describe Zend\Permissions\ACLs.
    ]]></xs:documentation>
    </xs:annotation>
    <xs:element name="acl">
        <xs:annotation>
            <xs:documentation>
                Root element of definition
            </xs:documentation>
        </xs:annotation>
        <xs:complexType>
            <xs:sequence>
                <xs:element name="roles" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            Containing element for roles
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="role" type="roleType" minOccurs="1"
                                maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="resources" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            Containing element for resources
                        </xs:documentation>
                    </xs:annotation>
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="resource" type="resourceType" minOccurs="1"
                                maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="rules" maxOccurs="1">
                    <xs:annotation>
                        <xs:documentation>
                            Containing element for rules
                        </xs:documentation>
                    </xs:annotation>                    
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="rule" type="ruleType" minOccurs="1"
                                maxOccurs="unbounded"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="roleType">
        <xs:annotation>
            <xs:documentation>
                Definition of a role
            </xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" default="GenericRole" use="optional"/>
                <xs:attribute name="parents" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="resourceType">
        <xs:annotation>
            <xs:documentation>
                Definition of a resource
            </xs:documentation>
        </xs:annotation>
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" type="xs:string" default="GenericResource" use="optional"/>
                <xs:attribute name="parent" type="xs:string" use="optional"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="ruleType">
        <xs:annotation>
            <xs:documentation>
                Definition of a rule
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="privilege" type="xs:string" minOccurs="0" maxOccurs="unbounded">
                <xs:annotation>
                    <xs:documentation>
                        A role may contain zero or more privileges
                    </xs:documentation>
                </xs:annotation>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="type" use="required" type="accessType"/>
        <xs:attribute name="roles" type="xs:string" use="optional" default="*"/>
        <xs:attribute name="resources" type="xs:string" use="optional" default="*"/>
        <xs:attribute name="assertion" type="xs:string" use="optional"/>
    </xs:complexType>

    <xs:simpleType name="accessType">
        <xs:annotation>
            <xs:documentation>
                Role access type enumeration
            </xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:token">
            <xs:enumeration value="ALLOW"/>
            <xs:enumeration value="DENY"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== abington/Zend-Acl-Xml-Builder/test/src/chippyash/Zend/Acl/Xml/fixtures/badtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<acl xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="zendacl.xsd">
    <!-- No roles defined - will fail validation-->
    <resources>
        <resource>login</resource>
        <resource type="chippyash\Test\Zend\Acl\Xml\Stubs\TestResourceStub">logout</resource>
        <resource type="GenericResource">dashboard</resource>
        <resource parent="dashboard">edit</resource>
    </resources>
    <rules>
        <rule type="DENY"/>
        <rule type="ALLOW" roles="*" resources="login" assertion="chippyash\Test\Zend\Acl\Xml\Stubs\TestAssertionStub"/>
        <rule type="ALLOW" roles="user,superadmin">
            <privilege>GET</privilege>
            <privilege>POST</privilege>
        </rule>
    </rules>
</acl>

=== abington/Zend-Acl-Xml-Builder/test/src/chippyash/Zend/Acl/Xml/fixtures/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<acl xmlns="http://zf4.biz/zendacl"
 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://zf4.biz/zendacl ../../../../../../../src/chippyash/Zend/Acl/Xml/xsd/zendacl.xsd">
    <roles>
        <role type="GenericRole">guest</role>
        <role parents="guest" type="chippyash\Test\Zend\Acl\Xml\Stubs\TestRoleStub">user</role>
        <role parents="user">admin</role>
        <role parents="user,admin">superadmin</role>
    </roles>
    <resources>
        <resource>login</resource>
        <resource type="chippyash\Test\Zend\Acl\Xml\Stubs\TestResourceStub">logout</resource>
        <resource type="GenericResource">dashboard</resource>
        <resource parent="dashboard">edit</resource>
    </resources>
    <rules>
        <rule type="DENY"/>
        <rule type="ALLOW" roles="*" resources="login" assertion="chippyash\Test\Zend\Acl\Xml\Stubs\TestAssertionStub"/>
        <rule type="ALLOW" roles="user,superadmin">
            <privilege>GET</privilege>
            <privilege>POST</privilege>
        </rule>
    </rules>
</acl>
